In [29]:
import pandas as pd

# Load data
df = pd.read_excel("Trade_Data.xlsx")

# 1. Drop completely empty columns
df = df.dropna(axis=1, how='all')

# 2. Drop irrelevant columns (you can adjust this)
cols_to_drop = [
    'typeCode', 'freqCode', 'refPeriodId',
    'reporterCode', 'partnerCode', 'partner2Code',
    'partner2ISO', 'partner2Desc',
    'classificationCode', 'classificationSearchCode',
    'isOriginalClassification', 'isLeaf',
    'customsCode', 'customsDesc',
    'mosCode', 'motCode',
    'qtyUnitCode', 'altQtyUnitCode',
    'isQtyEstimated', 'isAltQtyEstimated',
    'isNetWgtEstimated', 'isGrossWgtEstimated',
    'legacyEstimationFlag', 'isReported', 'isAggregate'
]

df = df.drop(columns=cols_to_drop, errors='ignore')

# 4. Rename columns for clarity
df = df.rename(columns={
    'reporterDesc': 'Country',
    'partnerDesc': 'partner_name',
    'cmdCode': 'product_code',
    'cmdDesc': 'product_description',
    'flowDesc': 'trade_flow',
    'motDesc': 'transport_mode',
    'primaryValue': 'trade_value',
    'refYear':'Year',
    'qty':'Quantity',
    'netWgt':'Net Weight'
})

# 5. Remove duplicates
df = df.drop_duplicates()

# 6. Convert types if needed
df['Year'] = df['Year'].astype(int)

# Save cleaned data
df.to_excel("Cleaned_TradeData.xlsx", index=False)

print("Data cleaned successfully!")
print(df.head())
#cleaning data changing features name into more detalied name

Data cleaned successfully!
   Year Country partner_name trade_flow  product_code  \
0  2016   India     thailand     Import        847130
1  2016   India     ethiopia     Import        847130
2  2016   India        qatar     Import        847130
3  2016   India      croatia     Import        847130
4  2016   India    indonesia     Import        847130

                                 product_description  Trade Value  Quantity  \
0  Automatic data processing machines; portable, ...       2671.0       3.0
1  Automatic data processing machines; portable, ...        740.0       2.0
2  Automatic data processing machines; portable, ...       2279.0       2.0
3  Automatic data processing machines; portable, ...        835.0       1.0
4  Automatic data processing machines; portable, ...        383.0       1.0

   Net Weight altQtyUnitAbbr  LPI_Merge_Year  LPI Score  Customs Score  \
0        14.0            NaN            2016   3.255100       3.105066
1         4.0            NaN            2016   2.376767       2.598943
2        12.0            NaN            2016   3.599232       3.551227
3         4.0            NaN            2016   3.160829       3.074242
4         2.0            NaN            2016   2.984537       2.688429

   Infrastructure Score  International Shipments Score  \
0              3.123670                       3.366940
1              2.117674                       2.562729
2              3.568039                       3.582678
3              2.989697                       3.115366
4              2.645161                       2.901908

   Logistics Competence and Quality Score  Tracking and Tracing Score  \
0                                3.135446                    3.203620
1                                2.367674                    2.178113
2                                3.543672                    3.503401
3                                3.214506                    3.164506
4                                3.000057                    3.192365

   Timeliness Score
0          3.559929
1          2.370804
2          3.832534
3          3.389019
4          3.459917

In [15]:
# Remove extra spaces in column names
df.columns = df.columns.str.strip()

# Check missing values
print(df.isnull().sum())

# Drop or fill missing values
df = df.dropna()
#checking how many missing values are there in each feature

Year                                         0
Country                                      0
partner_name                                 0
trade_flow                                   0
product_code                                 0
product_description                          0
Trade Value                                  0
qty                                          0
netWgt                                    2385
altQtyUnitAbbr                            5522
LPI_Merge_Year                               0
LPI Score                                 3866
Customs Score                             3866
Infrastructure Score                      3866
International Shipments Score             3866
Logistics Competence and Quality Score    3866
Tracking and Tracing Score                3866
Timeliness Score                          3866
dtype: int64

In [53]:
print(df.describe())

               Year   product_code   Trade Value      Quantity        netWgt  \
count  26595.000000   26595.000000  2.659500e+04  2.659500e+04  2.421000e+04
mean    2020.814890  630617.328182  7.380123e+07  1.162176e+08  1.271181e+08
std        2.676412  260071.084427  9.625935e+08  1.763927e+09  1.848337e+09
min     2016.000000  270900.000000  1.910000e-01  0.000000e+00  0.000000e+00
25%     2019.000000  310210.000000  1.462183e+04  6.000000e+01  1.347180e+02
50%     2021.000000  760110.000000  1.872168e+05  1.052700e+04  1.622661e+04
75%     2023.000000  848180.000000  2.819482e+06  4.618040e+05  4.397024e+05
max     2024.000000  901890.000000  5.272789e+10  9.200886e+10  9.200886e+10

       LPI_Merge_Year     LPI Score  Customs Score  Infrastructure Score  \
count    26595.000000  22729.000000   22729.000000          22729.000000
mean      2019.650085      3.259585       3.053938              3.215625
std          2.793026      0.622729       0.653703              0.758881
min       2016.000000      1.598322       1.111111              1.237654
25%       2018.000000      2.700000       2.500000              2.500000
50%       2018.000000      3.314780       3.051648              3.200000
75%       2023.000000      3.800000       3.663064              3.900000
max       2023.000000      4.300000       4.200000              4.600000

       International Shipments Score  Logistics Competence and Quality Score  \
count                   22729.000000                            22729.000000
mean                        3.149106                                3.258815
std                         0.534692                                0.679497
min                         1.362654                                1.394253
25%                         2.710675                                2.675926
50%                         3.300000                                3.300000
75%                         3.600000                                3.871699
max                         4.235000                                4.400000

       Tracking and Tracing Score  Timeliness Score        Export  \
count                22729.000000      22729.000000  2.659500e+04
mean                     3.322604          3.544050  4.080065e+07
std                      0.682184          0.567751  1.082220e+07
min                      1.513605          2.023799  2.240748e+07
25%                      2.751033          3.111029  3.389183e+07
50%                      3.400000          3.600000  4.097649e+07
75%                      3.960279          4.000000  5.127855e+07
max                      4.400000          4.795714  5.763932e+07

             Import   Total_Trade  Trade_Balance
count  2.659500e+04  2.659500e+04   2.659500e+04
mean   1.266098e+08  1.674104e+08  -8.580913e+07
std    5.864727e+07  6.094062e+07   5.830509e+07
min    7.667690e+07  1.248216e+08  -2.224893e+08
25%    7.770336e+07  1.275386e+08  -1.297417e+08
50%    1.079750e+08  1.358659e+08  -8.272368e+07
75%    1.644760e+08  1.992103e+08  -3.058510e+07
max    2.801286e+08  3.377679e+08  -2.539835e+07

In [55]:
print(df['trade_flow'].unique())
#building new Column from the type of Trade_flow which includes import or export

<StringArray>
['Import', 'Export']
Length: 2, dtype: str

In [56]:
df_pivot = df.pivot_table(
    values='Trade Value',
    index=['Country', 'Year'],
    columns='trade_flow'
).reset_index()

print(df_pivot.head())
#Checking how much india has imported or exported within the years

trade_flow Country  Year        Export        Import
0            India  2016  2.240748e+07  1.051312e+08
1            India  2017  2.795470e+07  1.317245e+08
2            India  2018  3.473428e+07  1.644760e+08
3            India  2019  3.389183e+07  1.433267e+08
4            India  2020  2.789089e+07  1.079750e+08

In [32]:
df_pivot['Total_Trade'] = df_pivot['Export'] + df_pivot['Import']
#adding a new column for total trade which is the sum of import and export

In [33]:
df

,Year,Country,partner_name,trade_flow,product_code,product_description,Trade Value,Quantity,Net Weight,altQtyUnitAbbr,LPI_Merge_Year,LPI Score,Customs Score,Infrastructure Score,International Shipments Score,Logistics Competence and Quality Score,Tracking and Tracing Score,Timeliness Score
0,2016,India,thailand,Import,847130,"Automatic data processing machines; portable, ...",2671.000,3.000,14.000,NaN,2016,3.255100,3.105066,3.123670,3.366940,3.135446,3.203620,3.559929
1,2016,India,ethiopia,Import,847130,"Automatic data processing machines; portable, ...",740.000,2.000,4.000,NaN,2016,2.376767,2.598943,2.117674,2.562729,2.367674,2.178113,2.370804
2,2016,India,qatar,Import,847130,"Automatic data processing machines; portable, ...",2279.000,2.000,12.000,NaN,2016,3.599232,3.551227,3.568039,3.582678,3.543672,3.503401,3.832534
3,2016,India,croatia,Import,847130,"Automatic data processing machines; portable, ...",835.000,1.000,4.000,NaN,2016,3.160829,3.074242,2.989697,3.115366,3.214506,3.164506,3.389019
4,2016,India,indonesia,Import,847130,"Automatic data processing machines; portable, ...",383.000,1.000,2.000,NaN,2016,2.984537,2.688429,2.645161,2.901908,3.000057,3.192365,3.459917
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30536,2024,India,"hong kong sar, china",Import,848180,"Taps, cocks, valves and similar appliances; fo...",88.803,4.311,4.311,kg,2023,4.000000,3.800000,4.000000,4.000000,4.000000,4.200000,4.100000
30537,2024,India,costa rica,Import,848180,"Taps, cocks, valves and similar appliances; fo...",536.593,26.049,26.049,kg,2023,2.900000,2.800000,2.700000,2.800000,2.900000,2.900000,3.200000
30538,2024,India,bulgaria,Import,848180,"Taps, cocks, valves and similar appliances; fo...",710.244,34.479,34.479,kg,2023,3.200000,3.100000,3.100000,3.000000,3.300000,3.300000,3.500000
30539,2024,India,bulgaria,Import,848180,"Taps, cocks, valves and similar appliances; fo...",725.176,35.204,35.204,kg,2023,3.200000,3.100000,3.100000,3.000000,3.300000,3.300000,3.500000
30540,2024,India,netherlands,Import,848180,"Taps, cocks, valves and similar appliances; fo...",1448.776,70.331,70.331,kg,2023,4.100000,3.900000,4.200000,3.700000,4.200000,4.200000,4.000000

In [26]:
df_final = df.merge(df_pivot, on=['Country', 'Year'], how='left')

print(df_final.head())
#merging the new columns and sorting them according to country and year to decrease ambiguity

   Year Country partner_name trade_flow  product_code  \
0  2016   India     thailand     Import        847130
1  2016   India     ethiopia     Import        847130
2  2016   India        qatar     Import        847130
3  2016   India      croatia     Import        847130
4  2016   India    indonesia     Import        847130

                                 product_description  Trade Value  Quantity  \
0  Automatic data processing machines; portable, ...       2671.0       3.0
1  Automatic data processing machines; portable, ...        740.0       2.0
2  Automatic data processing machines; portable, ...       2279.0       2.0
3  Automatic data processing machines; portable, ...        835.0       1.0
4  Automatic data processing machines; portable, ...        383.0       1.0

   netWgt altQtyUnitAbbr  ...  LPI Score  Customs Score  Infrastructure Score  \
0    14.0            NaN  ...   3.255100       3.105066              3.123670
1     4.0            NaN  ...   2.376767       2.598943              2.117674
2    12.0            NaN  ...   3.599232       3.551227              3.568039
3     4.0            NaN  ...   3.160829       3.074242              2.989697
4     2.0            NaN  ...   2.984537       2.688429              2.645161

   International Shipments Score  Logistics Competence and Quality Score  \
0                       3.366940                                3.135446
1                       2.562729                                2.367674
2                       3.582678                                3.543672
3                       3.115366                                3.214506
4                       2.901908                                3.000057

   Tracking and Tracing Score  Timeliness Score        Export        Import  \
0                    3.203620          3.559929  2.240748e+07  1.051312e+08
1                    2.178113          2.370804  2.240748e+07  1.051312e+08
2                    3.503401          3.832534  2.240748e+07  1.051312e+08
3                    3.164506          3.389019  2.240748e+07  1.051312e+08
4                    3.192365          3.459917  2.240748e+07  1.051312e+08

    Total_Trade
0  1.275386e+08
1  1.275386e+08
2  1.275386e+08
3  1.275386e+08
4  1.275386e+08

[5 rows x 21 columns]

In [34]:
df=df_final

In [35]:
df

,Year,Country,partner_name,trade_flow,product_code,product_description,Trade Value,Quantity,netWgt,altQtyUnitAbbr,...,LPI Score,Customs Score,Infrastructure Score,International Shipments Score,Logistics Competence and Quality Score,Tracking and Tracing Score,Timeliness Score,Export,Import,Total_Trade
0,2016,India,thailand,Import,847130,"Automatic data processing machines; portable, ...",2671.000,3.000,14.000,NaN,...,3.255100,3.105066,3.123670,3.366940,3.135446,3.203620,3.559929,2.240748e+07,1.051312e+08,1.275386e+08
1,2016,India,ethiopia,Import,847130,"Automatic data processing machines; portable, ...",740.000,2.000,4.000,NaN,...,2.376767,2.598943,2.117674,2.562729,2.367674,2.178113,2.370804,2.240748e+07,1.051312e+08,1.275386e+08
2,2016,India,qatar,Import,847130,"Automatic data processing machines; portable, ...",2279.000,2.000,12.000,NaN,...,3.599232,3.551227,3.568039,3.582678,3.543672,3.503401,3.832534,2.240748e+07,1.051312e+08,1.275386e+08
3,2016,India,croatia,Import,847130,"Automatic data processing machines; portable, ...",835.000,1.000,4.000,NaN,...,3.160829,3.074242,2.989697,3.115366,3.214506,3.164506,3.389019,2.240748e+07,1.051312e+08,1.275386e+08
4,2016,India,indonesia,Import,847130,"Automatic data processing machines; portable, ...",383.000,1.000,2.000,NaN,...,2.984537,2.688429,2.645161,2.901908,3.000057,3.192365,3.459917,2.240748e+07,1.051312e+08,1.275386e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26590,2024,India,"hong kong sar, china",Import,848180,"Taps, cocks, valves and similar appliances; fo...",88.803,4.311,4.311,kg,...,4.000000,3.800000,4.000000,4.000000,4.000000,4.200000,4.100000,4.711826e+07,7.770336e+07,1.248216e+08
26591,2024,India,costa rica,Import,848180,"Taps, cocks, valves and similar appliances; fo...",536.593,26.049,26.049,kg,...,2.900000,2.800000,2.700000,2.800000,2.900000,2.900000,3.200000,4.711826e+07,7.770336e+07,1.248216e+08
26592,2024,India,bulgaria,Import,848180,"Taps, cocks, valves and similar appliances; fo...",710.244,34.479,34.479,kg,...,3.200000,3.100000,3.100000,3.000000,3.300000,3.300000,3.500000,4.711826e+07,7.770336e+07,1.248216e+08
26593,2024,India,bulgaria,Import,848180,"Taps, cocks, valves and similar appliances; fo...",725.176,35.204,35.204,kg,...,3.200000,3.100000,3.100000,3.000000,3.300000,3.300000,3.500000,4.711826e+07,7.770336e+07,1.248216e+08
26594,2024,India,netherlands,Import,848180,"Taps, cocks, valves and similar appliances; fo...",1448.776,70.331,70.331,kg,...,4.100000,3.900000,4.200000,3.700000,4.200000,4.200000,4.000000,4.711826e+07,7.770336e+07,1.248216e+08

In [78]:
print(df.describe())
df.to_excel('Cleaned_Trade_Data.xlsx', index=False)
#saving my file

               Year   product_code   Trade Value      Quantity        netWgt  \
count  26595.000000   26595.000000  2.659500e+04  2.659500e+04  2.421000e+04
mean    2020.814890  630617.328182  7.380123e+07  1.162176e+08  1.271181e+08
std        2.676412  260071.084427  9.625935e+08  1.763927e+09  1.848337e+09
min     2016.000000  270900.000000  1.910000e-01  0.000000e+00  0.000000e+00
25%     2019.000000  310210.000000  1.462183e+04  6.000000e+01  1.347180e+02
50%     2021.000000  760110.000000  1.872168e+05  1.052700e+04  1.622661e+04
75%     2023.000000  848180.000000  2.819482e+06  4.618040e+05  4.397024e+05
max     2024.000000  901890.000000  5.272789e+10  9.200886e+10  9.200886e+10

       LPI_Merge_Year     LPI Score  Customs Score  Infrastructure Score  \
count    26595.000000  22729.000000   22729.000000          22729.000000
mean      2019.650085      3.259585       3.053938              3.215625
std          2.793026      0.622729       0.653703              0.758881
min       2016.000000      1.598322       1.111111              1.237654
25%       2018.000000      2.700000       2.500000              2.500000
50%       2018.000000      3.314780       3.051648              3.200000
75%       2023.000000      3.800000       3.663064              3.900000
max       2023.000000      4.300000       4.200000              4.600000

       International Shipments Score  Logistics Competence and Quality Score  \
count                   22729.000000                            22729.000000
mean                        3.149106                                3.258815
std                         0.534692                                0.679497
min                         1.362654                                1.394253
25%                         2.710675                                2.675926
50%                         3.300000                                3.300000
75%                         3.600000                                3.871699
max                         4.235000                                4.400000

       Tracking and Tracing Score  Timeliness Score        Export  \
count                22729.000000      22729.000000  2.659500e+04
mean                     3.322604          3.544050  4.080065e+07
std                      0.682184          0.567751  1.082220e+07
min                      1.513605          2.023799  2.240748e+07
25%                      2.751033          3.111029  3.389183e+07
50%                      3.400000          3.600000  4.097649e+07
75%                      3.960279          4.000000  5.127855e+07
max                      4.400000          4.795714  5.763932e+07

             Import   Total_Trade  Trade_Balance
count  2.659500e+04  2.659500e+04   2.659500e+04
mean   1.266098e+08  1.674104e+08  -8.580913e+07
std    5.864727e+07  6.094062e+07   5.830509e+07
min    7.667690e+07  1.248216e+08  -2.224893e+08
25%    7.770336e+07  1.275386e+08  -1.297417e+08
50%    1.079750e+08  1.358659e+08  -8.272368e+07
75%    1.644760e+08  1.992103e+08  -3.058510e+07
max    2.801286e+08  3.377679e+08  -2.539835e+07

In [ ]:
df_trade = pd.read_excel('Filtered_TradeData.xlsx')
df_lpi = pd.read_excel('Cleaned_LPI_Rounded_2.xlsx')
df_trade.rename(columns={'reporter_name': 'Country'}, inplace=True)
df_trade.rename(columns={'refYear': 'Year'}, inplace=True)
print(df_trade.columns)
df_merged = pd.merge(
    df_trade,
    df_lpi,
    on=['Country', 'Year'],   
    how='inner'               
)

# Save output
df_merged.to_excel('Merged_Data.xlsx', index=False)
#merging the the two data sets for analysis